// Tests for the command-line linter (bin/lint.js).
//
// The linter builds a real Program from the project's tsconfig rather than
// driving tsserver, so this verifies that path independently: passage errors map
// back onto .twee spans, exit codes are CI-appropriate, and typo detection has
// the same opt-in / false-positive-safe behaviour as the editor. It shares the
// analysis core with the plugin (tw-sugarcube-analyzer), so the tsserver smoke
// suite covers the same rules from the other side.
import { spawnSync } from "child_process";
import { mkdirSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { MAX_TYPE_LENGTH } from "tw-sugarcube-analyzer/analyzer.js";

const testDir = path.dirname(fileURLToPath(import.meta.url));

// The native-TS7 fallback fixture needs a resolvable `typescript` in its
// node_modules that LACKS the compiler API. node_modules is gitignored, so it's
// generated here rather than committed — otherwise a fresh checkout couldn't run
// this test.
function writeFakeTs7() {
  const dir = path.join(testDir, "fixture-fakets7", "node_modules", "typescript");
  mkdirSync(dir, { recursive: true });
  writeFileSync(path.join(dir, "package.json"), JSON.stringify({ name: "typescript", version: "7.0.99", main: "index.js" }));
  writeFileSync(path.join(dir, "index.js"),
    "// Stand-in for the native TS7 compiler: resolvable, but no in-process JS API.\nmodule.exports = { version: \"7.0.99\" };\n");
}
writeFakeTs7();

// The over-limit table is generated rather than committed, and sized from the
// analyzer's own constant: hardcoding a row count would quietly stop exceeding
// the cap the moment the cap moved, and the test would then pass by not
// triggering the thing it exists to check.
function writeOverLimitTable() {
  const row = (i) => {
    const n = String(i).padStart(3, "0");
    return `  { key: "item${n}", name: "Item Number ${n}", lower: "item number ${n}", price: ${i}, points: ${i % 7} },`;
  };
  // Each row serializes to appreciably more than its source length, so rows
  // worth MAX_TYPE_LENGTH characters of source overshoot the cap comfortably.
  const rows = [];
  for (let i = 0, len = 0; len < MAX_TYPE_LENGTH; i++) { rows.push(row(i)); len += rows[i].length; }
  writeFileSync(path.join(testDir, "fixture-downgrade", "big.ts"),
    "// Generated by test/lint-cli.mjs — a table too large to serialize into the\n" +
    "// augmentation, so its member must be reported as downgraded.\n" +
    `const huge = [\n${rows.join("\n")}\n] as const;\n\nsetup.huge = huge;\n`);
}
writeOverLimitTable();

// The same loss, but originating in a passage: the site has to be translated out
// of the virtual projection and back onto the .twee document, or the warning
// points at a file the author can't open. Generated for the same reason as the
// table above, and wide rather than deep because a `<<set>>` can't say `as
// const` — an array literal widens to a short type, so only a genuinely wide
// object still serializes long enough to trip the cap.
function writeOverLimitPassage() {
  const keys = [];
  for (let i = 0, len = 0; len < MAX_TYPE_LENGTH; i++) {
    keys.push(`key_number_${String(i).padStart(4, "0")}: ${i}`);
    len += keys[i].length;
  }
  writeFileSync(path.join(testDir, "fixture-downgrade-twee", "story.twee"),
    `:: Start\nSome prose, so the passage body doesn't start at the projection's origin.\n` +
    `<<set $huge to {${keys.join(", ")}}>>\nMore prose.\n`);
}
writeOverLimitPassage();

const repoRoot = path.dirname(testDir);
const CLI = path.join(repoRoot, "bin", "lint.js");

const results = [];
const check = (name, ok, detail) => {
  results.push({ name, ok });
  console.log(`${ok ? "  PASS" : "  FAIL"}  ${name}${ok || !detail ? "" : `\n        ${detail}`}`);
};

function lint(fixture, args = []) {
  const r = spawnSync(process.execPath, [CLI, path.join(testDir, fixture), ...args], { encoding: "utf8" });
  return { code: r.status, out: r.stdout || "", err: r.stderr || "" };
}

console.log("lint CLI\n");

// --- passage type error maps back to .twee ---------------------------------
{
  const r = lint("fixture-lint");
  check("a passage type error is reported", /Argument of type 'string' is not assignable/.test(r.out), r.out);
  check("...located in the .twee file, not the projection",
    /story\.twee:3:\d+/.test(r.out) && !/story\.twee\.ts/.test(r.out), r.out);
  check("exit code is 1 when there are findings", r.code === 1, `exit ${r.code}`);
}

// --- <<if>> narrows, and the spans still map through the nested blocks ------
// A closed `<<if>>` projects to a real TypeScript block. The guarded uses in
// this fixture are only clean because of the narrowing, the unguarded ones are
// only errors because it stops at the block — and the projection now nests, so
// the reported spans prove the position map survived it.
{
  const r = lint("fixture-twee-narrow");
  check("an <<if>>-guarded use of a nullable variable is clean",
    !/story\.twee:1[4-8]:/.test(r.out), r.out);
  check("the same use outside the guard is reported",
    /story\.twee:21:21\s+error\s+TS2345.*'Item \| null'/.test(r.out), r.out);
  check("the <<else>> branch gets the negated type",
    /story\.twee:26:21\s+error\s+TS2345.*'null'/.test(r.out), r.out);
  check("nothing else is reported", /2 problems/.test(r.out), r.out);
}

// --- a clean project exits 0 -----------------------------------------------
{
  const r = lint("fixture-lint-clean"); // reads passage-created variables, all valid
  check("a clean project reports nothing", /no problems found/.test(r.out), r.out);
  check("exit code is 0 when clean", r.code === 0, `exit ${r.code}: ${r.out}`);
}

// --- recovered types that depend on other recovered types ------------------
// The linter used to generate the augmentation exactly once, from a program
// where it was still empty. A member assigned from another recovered member
// (`<<set $hero to setup.makeHero()>>`) therefore came back `any` and every
// error downstream of it vanished — the extension squiggled, the linter passed.
// Generation must iterate to a fixed point, as the plugin does.
{
  const r = lint("fixture-lint-chained");
  check("a type recovered through another recovered type is resolved",
    /not assignable to type 'number'/.test(r.out), r.out);
  check("...and the finding maps to the .twee line that dereferences it",
    /story\.twee:6:\d+/.test(r.out), r.out);
  check("exit 1 on the chained-recovery finding", r.code === 1, `exit ${r.code}`);
  check("generation settles (no non-convergence warning)",
    !/did not settle/.test(r.err), r.err);
}

// --- <<script>> payloads are analyzed as the code they are ------------------
// A payload used to be read as prose, so its `_locals` became bogus
// `State.temporary` reads, its real statements were never projected, and this
// whole fixture linted clean: the type error inside the payload was invisible
// and the variable the payload creates was never recovered.
{
  const r = lint("fixture-lint-script", ["--typos"]);
  check("a type error inside a <<script>> payload is reported at its .twee line",
    /story\.twee:9:14\s+error\s+TS2345/.test(r.out), r.out);
  check("a variable created only by a <<script>> payload gets its type",
    /world\.ts:6:\d+\s+error\s+TS2322.*'number' is not assignable to type 'string'/.test(r.out), r.out);
  check("...and the payload's own locals are not mistaken for story variables",
    /2 problems/.test(r.out), r.out);
}

// --- typo detection is opt-in ----------------------------------------------
{
  const off = lint("fixture-typos");
  check("a typo is NOT reported without --typos", off.code === 0 && !/attck/.test(off.out),
    `exit ${off.code}: ${off.out}`);

  const on = lint("fixture-typos", ["--typos"]);
  check("a typo IS reported with --typos", /Property 'attck' does not exist/.test(on.out), on.out);
  // Count finding lines by their location prefix; the summary line says "error" too.
  check("...and only the typo — nothing legitimate",
    on.out.split("\n").filter((l) => /:\d+:\d+ {2}error/.test(l)).length === 1, on.out);
  check("exit 1 on a typo finding", on.code === 1, `exit ${on.code}`);
}

// --- false-positive safety: the classes that broke 0.4.0 -------------------
{
  // settings members (Setting API), passage <<set>> variables, and members
  // assigned in .ts must never be reported even with typos on.
  const r = lint("fixture-typos", ["--typos"]);
  check("settings / passage / .ts members are not called typos",
    !/'hp'|'volume'|'attack' does not exist/.test(r.out), r.out);
}

// --- Object.assign keeps its container open --------------------------------
{
  const r = lint("fixture-typos-assign", ["--typos"]);
  check("Object.assign suppresses typo detection for that container", r.code === 0, `exit ${r.code}: ${r.out}`);
}

// --- members created only by compound assignments are real members ----------
// `??=`/`||=`/`&&=` and `+=`-style operators create members too; a member that
// exists only through one of them must not be reported as a typo.
{
  const r = lint("fixture-typos-compound", ["--typos"]);
  check("a member created only via ??= is not a typo", !/'gold' does not exist/.test(r.out), r.out);
  check("a member created only via += is not a typo", !/'hp' does not exist/.test(r.out), r.out);
  // The container must still actually close — the real typo alongside them proves it.
  check("...but a genuine typo alongside compounds is still caught",
    /Property 'greeet' does not exist/.test(r.out), r.out);
  check("exit 1 on the compound fixture's real typo", r.code === 1, `exit ${r.code}`);
}

// --- a long recovered type is still a type ---------------------------------
// Types are serialized into the generated augmentation, so there is a cap to
// stop a pathological serialization from bloating it. The cap used to be 400
// characters, which an ordinary three-row item table exceeds — so real story
// data was silently typed `any` while the same array of bare strings worked.
{
  const r = lint("fixture-lint-bigtype");
  check("a long recovered member type is not degraded to any",
    /world\.ts:18:\d+.*Type 'number' is not assignable to type 'string'/.test(r.out), r.out);
  check("...and a short one alongside it still works",
    /world\.ts:19:\d+.*Type 'string' is not assignable to type 'number'/.test(r.out), r.out);
}

// --- a member that could not be typed says so -------------------------------
// Falling back to `any` costs the author every check on that member, at the one
// place they'd never think to look. Both reasons a fallback happens must be
// reported, on the assignment that caused it — and neither is the story's fault,
// so neither may fail the build.
{
  const r = lint("fixture-downgrade");
  check("an over-limit type is reported, not silently dropped",
    /big\.ts:\d+:\d+\s+warning .*'setup\.huge'.*over the \d+-character limit/.test(r.out), r.out);
  check("...with the size that blew the limit, so it's actionable",
    new RegExp(`serializes to \\d+ characters, over the ${MAX_TYPE_LENGTH}-character limit`).test(r.out), r.out);
  check("a module-scoped type is reported too",
    /world\.ts:5:\d+\s+warning .*'setup\.gift'.*import\(\.\.\.\)/.test(r.out), r.out);
  check("...and both point at the assignment that caused them",
    /world\.ts:5:7/.test(r.out), r.out);
  // The advice the warnings give is that a named GLOBAL type comes through, so
  // that had better be true — advice/1 must not itself warn.
  check("a named global type is not downgraded", !/setup\.charms/.test(r.out), r.out);
  check("warnings alone do not fail the build", r.code === 0, `exit ${r.code}: ${r.out}`);
  check("...and are counted as problems but not errors",
    /2 problems \(0 errors\)/.test(r.out), r.out);
}

// --- a downgrade inside a passage maps back to the .twee document -----------
{
  const r = lint("fixture-downgrade-twee");
  check("a passage downgrade is reported on the .twee, not the projection",
    /story\.twee:3:\d+\s+warning/.test(r.out) && !/story\.twee\.ts/.test(r.out), r.out);
  check("...naming the variable the way a passage writes it",
    /'State\.variables\.huge'/.test(r.out), r.out);
  // Column 7 is the `$huge` in `<<set $huge to ...>>`. The projection prepends
  // scaffolding, so an unmapped offset would land somewhere else entirely.
  check("...at the assignment's real column in the passage", /story\.twee:3:7/.test(r.out), r.out);
}

// --- downgrades are not reported when nothing is being typed ----------------
// --no-strict declares no member types at all, so `any` is the intended result
// rather than a loss; warning there would be noise on every member.
{
  const r = lint("fixture-downgrade", ["--no-strict"]);
  check("--no-strict reports no downgrades", !/typed 'any'/.test(r.out) && r.code === 0, `exit ${r.code}: ${r.out}`);
}

// --- a downgrade survives --json --------------------------------------------
{
  const r = lint("fixture-downgrade", ["--json"]);
  let parsed = null;
  try { parsed = JSON.parse(r.out); } catch (e) { /* leave null */ }
  const warn = parsed && parsed.findings.find((f) => f.category === "Warning");
  check("--json carries the downgrade with a rule id and no bogus TS code",
    !!warn && /^type-downgraded\//.test(warn.rule) && warn.code === null, r.out.slice(0, 300));
}

// --- a syntax error is reported (not just semantic errors) ------------------
// The linter used to collect only semantic diagnostics, so a plain parse error
// passed clean. Syntactic diagnostics must surface too.
{
  const r = lint("fixture-lint-syntax");
  check("a syntax error is reported", /TS1109|Expression expected/.test(r.out), r.out);
  check("exit code is 1 on a syntax error", r.code === 1, `exit ${r.code}`);
}

// --- machine-readable output ------------------------------------------------
{
  const r = lint("fixture-lint", ["--json"]);
  let parsed = null;
  try { parsed = JSON.parse(r.out); } catch (e) { /* leave null */ }
  check("--json emits parseable output with mapped locations",
    !!parsed && Array.isArray(parsed.findings) && parsed.findings.some((f) => /story\.twee$/.test(f.file) && f.line === 3),
    r.out.slice(0, 200));
}

// --- a project on the native TS 7.x compiler falls back gracefully ----------
// TS7 has no in-process compiler API, so loading the project's own TypeScript
// blindly would crash on ts.TypeFormatFlags. The fixture ships a fake TS 7.x
// (resolvable, no API) in its node_modules; the linter must fall back to the
// bundled TypeScript and still analyze correctly.
{
  const r = lint("fixture-fakets7");
  check("falls back to bundled TS when the project's is native 7.x",
    /native 7\.x|no in-process compiler API/.test(r.err), r.err || "(no notice on stderr)");
  check("...and still produces a real result", r.code === 0 && /no problems found/.test(r.out),
    `exit ${r.code}: ${r.out}`);
}

// --- all four tweego source extensions are analyzed ------------------------
// tweego recognizes .tw, .twee, .tw2, .twee2; the extension must cover the whole
// set, not just the two Twee 3 Language Tools associates.
{
  const r = lint("fixture-lint-ext");
  check("a .twee2 passage error is reported", /story\.twee2:2:\d+.*not assignable/.test(r.out), r.out);
  check("...and a .tw2 passage projects without spurious errors",
    !/extra\.tw2/.test(r.out) && r.out.split("\n").filter((l) => /:\d+:\d+  error/.test(l)).length === 1, r.out);
}

// --- the tool runs from any cwd (CI invokes it oddly) ----------------------
{
  const r = spawnSync(process.execPath, [CLI, path.join(testDir, "fixture-lint")], { encoding: "utf8", cwd: repoRoot });
  check("runs from a different cwd", r.status === 1 && /story\.twee/.test(r.stdout), `exit ${r.status}`);
}

const failed = results.filter((r) => !r.ok);
console.log(`\n${results.length - failed.length}/${results.length} checks passed`);
if (failed.length) {
  console.log("FAILED: " + failed.map((f) => f.name).join(", "));
  process.exit(1);
}
